name: Adachi Facility Checker

on:
  schedule:
    # 1時間おきに実行 (UTC表記なので日本時間の毎時0分)
    - cron: '0 * * * *'
  workflow_dispatch: # 手動実行ボタンも作成

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          TARGET_MAIL: ${{ secrets.TARGET_MAIL }}
        run: python main.py
